---
- name: Shutdown specific ports on Debian/Ubuntu
  hosts: all
  become: yes
  vars:
    ports: [8080]  # Default port list
  tasks:

    - name: Check if ufw is installed
      ansible.builtin.command: which ufw
      register: ufw_check
      ignore_errors: yes

    - name: Check if iptables is installed
      ansible.builtin.command: which iptables
      register: iptables_check
      ignore_errors: yes

    - name: Close ports using ufw (if available)
      ansible.builtin.ufw:
        rule: deny
        port: "{{ item }}"
        proto: tcp
      loop: "{{ ports }}"
      when: ufw_check.rc == 0

    - name: Close ports using iptables (if available)
      ansible.builtin.command: iptables -A INPUT -p tcp --dport {{ item }} -j DROP
      args:
        warn: false
      loop: "{{ ports }}"
      when: iptables_check.rc == 0

    - name: Save iptables rules (Debian/Ubuntu)
      ansible.builtin.command: iptables-save > /etc/iptables/rules.v4
      when: iptables_check.rc == 0
      args:
        warn: false

    - name: Reload ufw if active
      ansible.builtin.command: ufw reload
      when: ufw_check.rc == 0



#ansible-playbook update_port.yml -e 'ports=[8080,443,3306]'
#had nanti tolong di code langsung ya sebagai promt user + nanti ngelempar pake command gini jdinya pas exec command.
