- name: Run CIS Debian 11 Hardening
  hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Ensure Python 3 is installed
      raw: apt-get update -y && apt-get install -y python3 python3-apt
      register: python_bootstrap
      changed_when: "'Setting up python3' in python_bootstrap.stdout"
      failed_when: false

    - name: Set Python interpreter manually
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Gather facts
      setup:

  roles:
    - debian11-cis-defaultfalse