# install_nginx.yml
- name: Install and Start NGINX on Debian/Ubuntu
  hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Ensure Python 3 is installed
      raw: apt-get update -y && apt-get install -y python3 python3-apt
      register: python_bootstrap
      changed_when: "'Setting up python3' in python_bootstrap.stdout"
      failed_when: false

    - name: Set Python interpreter manually
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Gather facts
      setup:

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create /var/log/nginx directory (if missing)
      file:
        path: /var/log/nginx
        state: directory
        owner: www-data
        group: adm
        mode: '0755'

    - name: Ensure /etc/nginx/nginx.conf exists (only for Debian)
      copy:
        src: /usr/share/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        remote_src: yes
      when:
        - ansible_facts['distribution'] == "Debian"
        - not ansible_facts['distribution_version'].startswith("12")  # optional: skip for newer
      ignore_errors: yes

    - name: Test NGINX configuration
      command: nginx -t
      register: nginx_test
      failed_when: "'successful' not in nginx_test.stderr"

    - name: Enable NGINX on boot
      service:
        name: nginx
        enabled: yes

    - name: Start NGINX
      service:
        name: nginx
        state: started