# install_cockpit.yml
- name: Install Cockpit on Debian/Ubuntu
  hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Ensure Python 3 is installed
      raw: apt-get update -y && apt-get install -y python3 python3-apt
      register: python_bootstrap
      changed_when: "'Setting up python3' in python_bootstrap.stdout"
      failed_when: false

    - name: Set Python interpreter manually
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Gather facts
      setup:

  tasks:
    - name: Ensure Cockpit is installed
      apt:
        name: cockpit
        state: present
        update_cache: yes

    - name: Enable Cockpit service
      systemd:
        name: cockpit
        enabled: yes

    - name: Start Cockpit service
      systemd:
        name: cockpit
        state: started

    - name: Ensure firewall allows Cockpit (if UFW is active)
      ufw:
        rule: allow
        name: "Cockpit"
        port: 9090
        proto: tcp
      when: ansible_facts['distribution'] == "Ubuntu"
      ignore_errors: yes

    - name: Print access instructions
      debug:
        msg: "Cockpit is installed. Access it at https://{{ ansible_default_ipv4.address }}:9090"
