a = Analysis(['../frontend/main.py'],
             pathex=['.'],
             binaries=[],
             datas=[
                 ('../backend/files/*', 'backend/files'),
                 ('../backend/auto_harden/**/*', 'backend/auto_harden'),
                 ('../backend/patch_files/*', 'backend/patch_files'),
                 ('../backend/selected_harden/**/*', 'backend/selected_harden'),
                 ('../backend/models/*', 'backend/models'),
                 ('../backend/routes/*', 'backend/routes'),
                 ('../backend/utils/*', 'backend/utils'),
                 ('../backend/.env', 'backend'),
                 ('../frontend/.env', 'frontend'),
             ],
             hiddenimports=[
                'chardet',
                'idna',
                'certifi',
                'urllib3',
                'cmath',
            ],
             hookspath=['hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=None)
pyz = PYZ(a.pure, a.zipped_data, cipher=None)
exe = EXE(pyz, a.scripts, a.binaries, a.zipfiles, a.datas,
          name='MyApp',
          debug=False,
          strip=False,
          upx=True,
          console=True)
