- name: Uninstall NGINX on Debian/Ubuntu
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Ensure Python 3 is installed (required by Ansible)
      apt:
        name:
          - python3
          - python3-apt
        state: present
        update_cache: yes

    - name: Gather facts now that Python is installed
      setup:

    - name: Stop NGINX service if running
      service:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Disable NGINX service
      service:
        name: nginx
        enabled: no
      ignore_errors: yes

    - name: Uninstall NGINX
      apt:
        name: nginx
        state: absent
        purge: yes
      
    - name: Remove NGINX config directory (if still exists)
      file:
        path: /etc/nginx
        state: absent
      ignore_errors: yes

    - name: Remove NGINX log directory (if still exists)
      file:
        path: /var/log/nginx
        state: absent
      ignore_errors: yes